version: '3'

services:
  client:
    build:
      context: './Client'
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app

  server:
    build:
      context: './Server'
    ports:
      - "8080:8080"
    networks:
      - app
networks:
  app:
    driver: bridge
    